---


- hosts: trial0 
  tasks:
    - name: install java
      yum:
        name: java-1.8.0-openjdk
        state: latest
       
    - name: creating a repository file for cassandra db
      file: 
        path: /etc/yum.repos.d/cassandra.repo
        state: touch
  
    - name: insert repo data in cassandra repo
      blockinfile: 
        path: /etc/yum.repos.d/cassandra.repo
        block: |
          [cassandra]
          name=Apache Cassandra
          baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://www.apache.org/dist/cassandra/KEYS

    - name: install cassandra database
      yum:
        name: cassandra
        state: latest

    
    - name: enable the service cassandra
      service:
        name: cassandra
        state: started
        enabled: true
 
    - name: allow cassandra through firewall
      firewalld: 
        service: cassandra
        state: enabled
        permanaent: yes

    - name: firewall reload
      service:
        name: firewalld
        satate: reloaded
