---

- hosts: ntp-client
  tasks: 
    - name: download postgresql repo
      yum: 
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: install postgresql
      yum:
        name: postgresql12-server
        state: latest

    - name: install postgresql-contrib
      yum:
        name: postgresql12-contrib

    - name: install pg-repack
      yum:
        name: pg_repack12
        state: latest

    - name: create data cluster
      command: /usr/pgsql-12/bin/postgresql-12-setup initdb

    - name: install pre-requisites
      yum:
        name: python-psycopg2
        state: latest

    - name: start postgres
      service:
        name: postgresql-12
        state: started
        enabled: true
    
    - name: create a new database
      become_user: postgres
      postgresql_db:
        name: db_abc123
        
 
    - name: create a new user for postgres
      become_user: postgres
      postgresql_user:
        name: admin
        db: postgres
        role_attr_flags: CREATEDB,SUPERUSER,CREATEROLE,REPLICATION
      
    - name: apply role on database
      become_user: postgres
      postgresql_privs:
        db: db_abc123
        privs: ALL
        type: database
        role: admin,postgres
        grant_option: yes
