---

- hosts: slave00
  tasks:
    - name: install docker required package
      yum:
        name: yum-utils,device-mapper-persistent-data,lvm2
        state: latest
    
    - name: download docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: install docker
      yum:
        name: docker-ce
        state: latest

    - name: install docker pyhton for docker
      yum: 
        name: docker-python
        state: latest
        
    - name: start the docker service
      service: 
        name: docker
        enabled: true
        state: started
   

