---



- name: install mysql server
  yum:
    name: mysql-server
    state: present
- name: install mysql-python (this is required for the task remove anonymous user)
  yum:
    state: MySQL-python
    state: present


