---


- name: download mysql community repo v 5.5 for centos 7
  when: ( mysql-version == "5.5" )
  get_url:
    url: http://repo.mysql.com/yum/mysql-5.5-community/el/7/x86_64/mysql-community-devel-5.5.62-2.el7.x86_64.rpm
    dest: /tmp
    
- name: install mysql community repo v 5.5 for centos 7
  when: ( mysql-version == "5.5" )
  command: /usr/bin/rpm -ivh /tmp/mysql-community-devel-5.5.62-2.el7.x86_64.rpm


- name: download mysql community repo v 5.6 for centos 7
  get_url:
    url: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/mysql-community-devel-5.6.47-2.el7.x86_64.rpm
    dest: /tmp
  when: ( mysql-version == "5.6" )
- name: install mysql community repo v 5.6 for centos 7
  yum:
    name: /tmp/mysql-community-devel-5.6.47-2.el7.x86_64.rpm
    state: present
  when: ( mysql-version == "5.6" )
- name: download mysql community repo v 5.7 for centos 7
  when: ( mysql-version == "5.7" )
  get_url:
    url: http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql-community-devel-5.7.9-1.el7.x86_64.rpm 
    dest: /tmp

- name: install mysql community repo v 5.7 for centos 7
  when: ( mysql-version == "5.7" )
  command: /usr/bin/rpm -ivh /tmp/mysql-community-devel-5.7.9-1.el7.x86_64.rpm

- name: running an update command
  command: yum -y update
 






